-- =============================================
-- profiles テーブル
-- auth.users に紐づくアプリ固有のユーザー情報
-- =============================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id          UUID           PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name        VARCHAR(255),
  created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- =============================================
-- chat_messages テーブル
-- ユーザーと AI の対話履歴
-- =============================================
CREATE TABLE IF NOT EXISTS public.chat_messages (
  id          BIGINT         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id     UUID           REFERENCES auth.users(id),
  role        VARCHAR(50)    NOT NULL,
  message     TEXT           NOT NULL,
  created_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- =============================================
-- suggestions テーブル
-- AI が生成した英語表現の提案（1 メッセージに複数紐付く）
-- =============================================
CREATE TABLE IF NOT EXISTS public.suggestions (
  id                    BIGINT  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  chat_message_id       BIGINT  NOT NULL REFERENCES public.chat_messages(id) ON DELETE CASCADE,
  english_sentence      TEXT    NOT NULL,
  japanese_translation  TEXT    NOT NULL,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =============================================
-- bookmarks テーブル
-- ユーザーがブックマークした提案（中間テーブル）
-- =============================================
CREATE TABLE IF NOT EXISTS public.bookmarks (
  id            BIGINT  PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id       UUID    NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  suggestion_id BIGINT  NOT NULL REFERENCES public.suggestions(id) ON DELETE CASCADE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, suggestion_id)
);

-- =============================================
-- Row Level Security を有効化
-- =============================================
ALTER TABLE public.profiles      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suggestions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookmarks     ENABLE ROW LEVEL SECURITY;

-- =============================================
-- RLS ポリシー: profiles
-- =============================================
CREATE POLICY "自分のプロフィールを参照できる" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "自分のプロフィールを更新できる" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "自分のプロフィールを作成できる" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

-- =============================================
-- RLS ポリシー: chat_messages
-- =============================================
CREATE POLICY "自分のメッセージを参照できる" ON public.chat_messages
  FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "自分のメッセージを作成できる" ON public.chat_messages
  FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL);

-- =============================================
-- RLS ポリシー: suggestions
-- =============================================
CREATE POLICY "自分のメッセージに紐づく提案を参照できる" ON public.suggestions
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.chat_messages cm
      WHERE cm.id = chat_message_id
        AND (cm.user_id = auth.uid() OR cm.user_id IS NULL)
    )
  );

CREATE POLICY "提案を作成できる" ON public.suggestions
  FOR INSERT WITH CHECK (true);

-- =============================================
-- RLS ポリシー: bookmarks
-- =============================================
CREATE POLICY "自分のブックマークを参照できる" ON public.bookmarks
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "自分のブックマークを作成できる" ON public.bookmarks
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "自分のブックマークを削除できる" ON public.bookmarks
  FOR DELETE USING (auth.uid() = user_id);

-- =============================================
-- ユーザー登録時に profiles を自動作成するトリガー
-- =============================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (NEW.id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
